### ISSUE TITLE
Complete Corresponding Source + Build instructions/scripts

### ISSUE THREAD

**Issue by davelab6** [s-a/digital-numbers-font#3]
Source files are defined as the preferred form of modification, plus reproducible build instructions or scripts. 

While some SVGs are included in the `/src` directory, its not clear how to build a TTF from them :)

**Comment by s-a** [comment]
This is true. So far build instructions are hidden in this file. https://github.com/s-a/digital-numbers-font/blob/gh-pages/demo/Read%20Me.txt.

I would need some time to reverse engineer https://github.com/s-a/digital-numbers-font/blob/gh-pages/demo/selection.json and research a cross platform font build system. Since I have nothing found yet I simply used this online service. https://icomoon.io

**Comment by davelab6** [comment]
There are some fontforge scripts to do this in fontforge src repo
